from datetime import datetime, date
from typing import List, Optional

from Models import TimerSession
from Models.enums import SessionType


class ITimerSessionRepository:

    def add(self, session: TimerSession) -> None: ...

    def get_by_id(self, session_id: int) -> Optional[TimerSession]: ...

    def get_all(self) -> List[TimerSession] : ...

    def update(self, session: TimerSession) -> None: ...

    def delete(self, session_id: int) -> None: ...

    def get_active_session(self) -> Optional[TimerSession]: ...

    def get_by_task_id(self, task_id: int) -> List[TimerSession]: ...

    def get_by_period(self, start: datetime, end: datetime) -> List[TimerSession]: ...

    def get_by_date(self, target_date: date) -> List[TimerSession]: ...

    def get_total_duration(self, start: datetime, end: datetime, session_type: Optional[SessionType] = None) -> int: ...


