from typing import List, Optional
from Models import Note

class INoteRepository:
    def add(self, note: Note) -> None: ...
    def get_by_id(self, note_id: int) -> Optional[Note]: ...
    def get_all(self) -> List[Note]: ...
    def update(self, note: Note) -> None: ...
    def delete(self, note_id: int) -> None: ...
    def get_by_task_id(self, task_id: int) -> List[Note]: ...