from typing import List, Optional
from Models import Note, Task
from PySide6.QtWidgets import QWidget

class INoteService:
    def add(self, note: Note) -> None: ...
    def update(self, note: Note) -> None: ...
    def delete(self, note_id: int) -> None: ...
    def get_all(self) -> List[Note]: ...
    def get_by_task(self, task_id: int) -> List[Note]: ...
