from typing import List, Optional
from Models import TimerSession

class ISessionService:
    def add(self, session: TimerSession) -> None: ...
    def update(self, session: TimerSession) -> None: ...
    def get_by_task(self, task_id: int) -> List[TimerSession]: ...
    def delete(self, session_id: int) -> None: ...