from typing import List, Optional
from datetime import date
from Models import Task
from Models.enums import TaskStatus, TaskPeriodType

class ITaskRepository:
    def add(self, task: Task) -> None: ...
    def get_by_id(self, task_id: int) -> Optional[Task]: ...
    def get_all(self) -> List[Task]: ...
    def update(self, task: Task) -> None: ...
    def delete(self, task_id: int) -> None: ...
    def get_tasks_for_date(self, target_date: date) -> List[Task]: ...
    def get_by_status(self, status: TaskStatus) -> List[Task]: ...
    def get_by_period_type(self, period_type: TaskPeriodType) -> List[Task]: ...