from typing import List, Optional
from Models import Task

class ITaskService:
    def get_all(self) -> List[Task]: ...
    def get_for_today(self) -> List[Task]: ...
    def add(self, task: Task) -> None: ...
    def update(self, task: Task) -> None: ...
    def delete(self, task_id: int) -> None: ...
    def complete(self, task_id: int) -> None: ...