from typing import Any

class ITrayService:
    def setup_tray(self, window: Any, view_model: Any, icon_path: str) -> None: ...
    def hide_tray(self) -> None: ...
    def show_message(self, title: str, msg: str, icon: int = 1, msecs: int = 2000) -> None: ...